/**
 ****************************************************************************************
 *
 * @file user_MCP9808.c
 *
 * @brief MCP9808 functions
 *
 * Copyright (C) 2018 Dialog Semiconductor. This computer program or computer programs included in this package ("Software") include confidential, proprietary information of Dialog Semiconductor. All Rights Reserved.
 * 
 * THIS SOFTWARE IS AN UNOFFICIAL RELEASE FROM DIALOG SEMICONDUCTOR (‘DIALOG’) AND MAY ONLY BE USED BY RECIPIENT AT ITS OWN RISK AND WITHOUT SUPPORT OF ANY KIND.  THIS SOFTWARE IS SOLELY FOR USE ON AUTHORIZED DIALOG PRODUCTS AND PLATFORMS.  RECIPIENT SHALL NOT TRANSMIT ANY SOFTWARE SOURCE CODE TO ANY THIRD PARTY WITHOUT DIALOG’S PRIOR WRITTEN PERMISSION.
 * 
 * UNLESS SET FORTH IN A SEPARATE AGREEMENT, RECIPIENT ACKNOWLEDGES AND UNDERSTANDS THAT TO THE FULLEST EXTENT PERMITTED BY LAW, THE SOFTWARE IS DELIVERED “AS IS”, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT, AND ALL WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, CUSTOM OR USAGE IN TRADE. FOR THE SAKE OF CLARITY, DIALOG AND ITS AFFILIATES AND ITS AND THEIR SUPPLIERS DO NOT WARRANT, GUARANTEE OR MAKE ANY REPRESENTATIONS (A) REGARDING THE USE, OR THE RESULTS OF THE USE, OF THE LICENSED SOFTWARE IN TERMS OF CORRECTNESS, COMPLETENESS, ACCURACY, RELIABILITY OR OTHERWISE, AND (B) THAT THE LICENSED SOFTWARE HAS BEEN TESTED FOR COMPLIANCE WITH ANY REGULATORY OR INDUSTRY STANDARD, INCLUDING, WITHOUT LIMITATION, ANY SUCH STANDARDS PROMULGATED BY THE FCC OR OTHER LIKE AGENCIES.
 * 
 * IN NO EVENT SHALL DIALOG BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 *
 ****************************************************************************************
 */

#include "user_MCP9808.h"
#include "user_i2c.h"
#include "gpio.h"

void init_MCP9808(uint8_t address){
	RESERVE_GPIO(,MCP9808_SDA_PORT, MCP9808_SDA_PIN, PID_I2C_SDA);
	RESERVE_GPIO(,MCP9808_SCL_PORT, MCP9808_SCL_PIN, PID_I2C_SCL);
	
	GPIO_ConfigurePin(MCP9808_SDA_PORT, MCP9808_SDA_PIN, INPUT_PULLUP, PID_I2C_SDA, true);
	GPIO_ConfigurePin(MCP9808_SCL_PORT, MCP9808_SCL_PIN, INPUT_PULLUP, PID_I2C_SCL, true);
	
	user_i2c_init(MCP9808_I2C_ADDRESS, I2C_7BIT_ADDR, I2C_FAST, I2C_1BYTE_REGISTER, I2C_1BYTE_ADDR); //Init with one byte registers as
																																																	 //the resolution register is 8 bit
	user_i2c_write_reg(0x8, 0x3); //Set the resolution to maximum                                    
	user_i2c_set_register_width(I2C_2BYTES_REGISTER);//Change to two byte registers for the temperature data
}

int16_t read_MCP9808(){
	return user_i2c_read_reg(5) & 0xFFF; //Register 5 contains 12 bits of temperature data
}
