/**
 ****************************************************************************************
 *
 * @file wkp_button.c
 *
 * @brief Wake up button source code
 *
 * Copyright (c) 2015-2018 Dialog Semiconductor. All rights reserved.
 *
 * This software ("Software") is owned by Dialog Semiconductor.
 *
 * By using this Software you agree that Dialog Semiconductor retains all
 * intellectual property and proprietary rights in and to this Software and any
 * use, reproduction, disclosure or distribution of the Software without express
 * written permission or a license agreement from Dialog Semiconductor is
 * strictly prohibited. This Software is solely for use on or in conjunction
 * with Dialog Semiconductor products.
 *
 * EXCEPT AS OTHERWISE PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, THE
 * SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. EXCEPT AS OTHERWISE
 * PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, IN NO EVENT SHALL
 * DIALOG SEMICONDUCTOR BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL,
 * OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
 * USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THE SOFTWARE.
 *
 ****************************************************************************************
 */
 #ifdef USER_WAKEUP_EXAMPLE
 
#include "wkupct_quadec.h"
#include "gpio.h"
#include "app_default_handlers.h"
#include "rwip_config.h"
#include "app_api.h"
#include "user_barebone.h"
#include "user_periph_setup.h"
#include "user_callback_config.h"
#include "user_wakeup_example.h"
#include "wkupct_quadec.h"
#include "arch_console.h"

/**
 ****************************************************************************************
 * @brief Button press callback function. Registered in WKUPCT driver.
 * @return void
 ****************************************************************************************
 */
void app_wakeup_press_cb(void)
{
		SetBits16(WKUP_CTRL_REG, WKUP_ENABLE_IRQ, 1); //Resets interupt
		if (arch_ble_ext_wakeup_get())
    {
        arch_set_sleep_mode(ARCH_SLEEP_OFF);
        arch_ble_force_wakeup();	
        arch_ble_ext_wakeup_off();
			
				if (GetBits16(SYS_STAT_REG, PER_IS_DOWN))
				{
						periph_init();
				}
				
				// If wakeup is generated by button P0_6
				if(GPIO_GetPinStatus(GPIO_BUTTON_PORT, GPIO_BUTTON_PIN))						
				{
						GPIO_SetActive(GPIO_LED_PORT, GPIO_LED_PIN);										// Turn the LED on to indicate the interrupt source is P0_6
						#ifdef CFG_PRINTF
								arch_printf("\n\n\rWakeup source: P0_6");
						#endif
				}
				// If wakeup is generated by button P1_1
				else if (GPIO_GetPinStatus(GPIO_BUTTON2_PORT, GPIO_BUTTON2_PIN))
				{
						#ifdef CFG_PRINTF
								arch_printf("\n\n\rWakeup source: P1_1");
						#endif
				}
		
				// If state is idle, start advertising
				if (ke_state_get(TASK_APP) == APP_CONNECTABLE)
				{
						user_app_adv_start();
				}
		}
		
		// If the system is awake, put it to sleep
		else if (!arch_ble_ext_wakeup_get())
		{
				#ifdef CFG_PRINTF
						arch_printf("\n\n\rSystem going to sleep");
				#endif
				GPIO_SetInactive(GPIO_LED_PORT, GPIO_LED_PIN);
			
				#ifdef SLEEP_WITHOUT_ADVERTISING
						app_easy_gap_advertise_stop();
				#endif
			
				arch_set_sleep_mode(ARCH_EXT_SLEEP_ON);				
				arch_ble_ext_wakeup_on();
		}
}

/**
 ****************************************************************************************
 * @brief Sets two buttons as wakeup trigger
 * @return void
 ****************************************************************************************
*/
void user_wakeup_example_init(void)
{
		wkupct_enable_irq((WKUPCT_PIN_SELECT(GPIO_BUTTON2_PORT, GPIO_BUTTON2_PIN) | WKUPCT_PIN_SELECT(GPIO_BUTTON_PORT, GPIO_BUTTON_PIN)), 						// When enabling more than one interruptsource use OR bitoperation. WKUPCT_PIN_SELECT will make sure the appropriate bit in the register is set. 
											(WKUPCT_PIN_POLARITY(GPIO_BUTTON2_PORT, GPIO_BUTTON2_PIN, 1) | WKUPCT_PIN_POLARITY(GPIO_BUTTON_PORT, GPIO_BUTTON_PIN, 1)),	// When enabling more than one interruptsource use OR bitoperation. WKUPCT_PIN_POLARITY will make sure the appriopriate bit in the register is set.
											1,																																																													// Number of events needed to trigger interrupt
											30);																																																												// Debounce time ranging from 0 to 63
	
		wkupct_register_callback(app_wakeup_press_cb);	// sets this function as wake-up interrupt callback
}

#endif
