/**
 ****************************************************************************************
 *
 * @file user_empty_peripheral_template.c
 *
 * @brief Empty peripheral template project source code.
 *
 * Copyright (c) 2012-2019 Dialog Semiconductor. All rights reserved.
 *
 * This software ("Software") is owned by Dialog Semiconductor.
 *
 * By using this Software you agree that Dialog Semiconductor retains all
 * intellectual property and proprietary rights in and to this Software and any
 * use, reproduction, disclosure or distribution of the Software without express
 * written permission or a license agreement from Dialog Semiconductor is
 * strictly prohibited. This Software is solely for use on or in conjunction
 * with Dialog Semiconductor products.
 *
 * EXCEPT AS OTHERWISE PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, THE
 * SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. EXCEPT AS OTHERWISE
 * PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, IN NO EVENT SHALL
 * DIALOG SEMICONDUCTOR BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL,
 * OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
 * USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THE SOFTWARE.
 *
 ****************************************************************************************
 */

/**
 ****************************************************************************************
 * @addtogroup APP
 * @{
 ****************************************************************************************
 */
#include "rwip_config.h"             // SW configuration


/*
 * INCLUDE FILES
 ****************************************************************************************
 */

#include "custs1.h"
#include "custs1_task.h"
#include "gpio.h"
#include "user_custs1_def.h"
#include "user_periph_setup.h"
#include "ble_notify_button_wakeup.h"
#include "wkupct_quadec.h"

/*
 * DEFINITIONS
 ****************************************************************************************
 */

#define WAKEUP_PINS                 (WKUPCT_PIN_SELECT(GPIO_SW2_PORT, GPIO_SW2_PIN) | WKUPCT_PIN_SELECT(GPIO_SW3_PORT, GPIO_SW3_PIN))
#define WAKEUP_POLARITIES           (WKUPCT_PIN_POLARITY(GPIO_SW2_PORT, GPIO_SW2_PIN, WKUPCT_PIN_POLARITY_LOW) | WKUPCT_PIN_POLARITY(GPIO_SW3_PORT, GPIO_SW3_PIN, WKUPCT_PIN_POLARITY_LOW))
#define WAKEUP_EVENTS_TO_TRIGGER    1
#define WAKEUP_DEBOUNCE_MS          30
/*
 * FUNCTION DECLARATIONS
 ****************************************************************************************
*/ 

// Interrupt initialization function declarations
void GPIO_1_UP_ISR(void);
void GPIO_1_STOP_ISR(void);
void GPIO_1_BACK_ISR(void);
 
/*
 * FUNCTION DEFINITIONS
 ****************************************************************************************
*/
/* Send the second command */

void app_wakeup_press_cb(void)
{
#if !defined (__DA14531__)
    if (GetBits16(SYS_STAT_REG, PER_IS_DOWN))
#endif
    {
        periph_init();
    }

    arch_ble_force_wakeup();	

    // If wakeup is generated by button P0_6
    if(!GPIO_GetPinStatus(GPIO_SW3_PORT, GPIO_SW3_PIN))						
    {
        app_easy_wakeup_set(GPIO_1_UP_ISR);
    }
    // If wakeup is generated by button P1_1
    else if (!GPIO_GetPinStatus(GPIO_SW2_PORT, GPIO_SW2_PIN))
    {
        app_easy_wakeup_set(GPIO_1_STOP_ISR);
    }

    wkupct_enable_irq(WAKEUP_PINS, WAKEUP_POLARITIES, WAKEUP_EVENTS_TO_TRIGGER,
                      WAKEUP_DEBOUNCE_MS);
        
    app_easy_wakeup();

}

void GPIO_1_UP_ISR(void)
{
    uint8_t lego_up_cmd[] = {0x05, 0x00, 0x45, 0x00, 0x01};
    uint8_t lego_up_cmd_len = sizeof(lego_up_cmd)/sizeof(lego_up_cmd[0]);
	
    struct custs1_val_ntf_ind_req *req = KE_MSG_ALLOC_DYN(CUSTS1_VAL_NTF_REQ,
                                                          prf_get_task_from_id(TASK_ID_CUSTS1),
                                                          TASK_APP,
                                                          custs1_val_ntf_ind_req,
                                                          DEF_SVC1_CTRL_POINT_CHAR_LEN);
		
    req->handle = SVC1_IDX_CONTROL_POINT_VAL;
    req->length = lego_up_cmd_len;
    req->notification = true;
    memcpy(req->value, &lego_up_cmd, lego_up_cmd_len);
		
    ke_msg_send(req);
}

void GPIO_1_STOP_ISR(void)
{
    uint8_t lego_up_cmd[] = {0x05, 0x00, 0x45, 0x00, 0x7f};
    uint8_t lego_up_cmd_len = sizeof(lego_up_cmd)/sizeof(lego_up_cmd[0]);
	
    struct custs1_val_ntf_ind_req *req = KE_MSG_ALLOC_DYN(CUSTS1_VAL_NTF_REQ,
                                                          prf_get_task_from_id(TASK_ID_CUSTS1),
                                                          TASK_APP,
                                                          custs1_val_ntf_ind_req,
                                                          DEF_SVC1_CTRL_POINT_CHAR_LEN);
		
    req->handle = SVC1_IDX_CONTROL_POINT_VAL;
    req->length = lego_up_cmd_len;
    req->notification = true;
    memcpy(req->value, &lego_up_cmd, lego_up_cmd_len);

    ke_msg_send(req);
}

/* User defined behavior for handling client's requests */
void user_catch_rest_hndl(ke_msg_id_t const msgid,
                          void const *param,
                          ke_task_id_t const dest_id,
                          ke_task_id_t const src_id)
{
	uint8_t	lego_brick_wr_1[] = {0x04, 0x00, 0x08, 0x06};
	uint8_t lego_15_cmd_1[] = {0x0f, 0x00, 0x04, 0x00, 0x01, 0x37, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x10};

	switch(msgid)
	{
        case CUSTS1_VAL_WRITE_IND:
        {
            struct custs1_val_write_ind const *msg_param = (struct custs1_val_write_ind const *)(param);

            switch (msg_param->handle)
            {
                case SVC1_IDX_CONTROL_POINT_VAL:
                    if(!memcmp(&lego_brick_wr_1[0], &msg_param->value[0], msg_param->length)) {
                        uint8_t lego_15_cmd_len = sizeof(lego_15_cmd_1)/sizeof(lego_15_cmd_1[0]);

                        struct custs1_val_ntf_ind_req *req = KE_MSG_ALLOC_DYN(CUSTS1_VAL_NTF_REQ,
                                                                              prf_get_task_from_id(TASK_ID_CUSTS1),
                                                                              TASK_APP,
                                                                              custs1_val_ntf_ind_req,
                                                                              DEF_SVC1_CTRL_POINT_CHAR_LEN);
                        // First message
                        req->handle = SVC1_IDX_CONTROL_POINT_VAL;
                        req->length = lego_15_cmd_len;
                        req->notification = true;
                        memcpy(req->value, &lego_15_cmd_1, lego_15_cmd_len);
                        ke_msg_send(req);
                    }
                    break;

                default:
                    break;
                }
			}
			break;
			
			default:
                break;
	}
}

void user_on_connection(uint8_t connection_idx, struct gapc_connection_req_ind const *param)
{
    wkupct_enable_irq(WAKEUP_PINS, WAKEUP_POLARITIES, WAKEUP_EVENTS_TO_TRIGGER,
                      WAKEUP_DEBOUNCE_MS);

    wkupct_register_callback(app_wakeup_press_cb);	// sets this function as wake-up interrupt callback	

    default_app_on_connection(connection_idx, param);
}

void user_on_disconnect( struct gapc_disconnect_ind const *param )
{
    default_app_on_disconnect(param);
}


/// @} APP
